CREATE TABLE `influencer_sentiment` (
	`id` int AUTO_INCREMENT NOT NULL,
	`modelKey` varchar(64) NOT NULL,
	`influencerName` varchar(128) NOT NULL,
	`platform` varchar(64) NOT NULL,
	`followers` varchar(32),
	`sentiment` varchar(32) NOT NULL,
	`sentimentScore` float,
	`keyThemesJson` json,
	`summary` text,
	`sourceUrl` varchar(512),
	`publishedDate` date,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `influencer_sentiment_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `model_configs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`modelKey` varchar(64) NOT NULL,
	`make` varchar(64) NOT NULL,
	`model` varchar(128) NOT NULL,
	`yearMin` smallint NOT NULL,
	`yearMax` smallint NOT NULL,
	`totalUnitsProduced` varchar(128),
	`engineSpec` varchar(256),
	`originalUkPriceGbp` varchar(64),
	`gpfYear` smallint,
	`investmentVerdict` varchar(32) DEFAULT 'consider',
	`iivWeightsJson` json,
	`colourDesirabilityJson` json,
	`standardEquipmentJson` json,
	`optionalEquipmentJson` json,
	`isPublic` boolean NOT NULL DEFAULT false,
	`isActive` boolean NOT NULL DEFAULT true,
	`sortOrder` smallint DEFAULT 0,
	`heroImageUrl` varchar(512),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `model_configs_id` PRIMARY KEY(`id`),
	CONSTRAINT `model_configs_modelKey_unique` UNIQUE(`modelKey`)
);
--> statement-breakpoint
CREATE TABLE `model_llm_content` (
	`id` int AUTO_INCREMENT NOT NULL,
	`modelKey` varchar(64) NOT NULL,
	`investmentVerdict` varchar(32) NOT NULL DEFAULT 'consider',
	`investmentHeadline` text,
	`investmentReasoning` text,
	`valueDriversJson` json,
	`valueDetractorsJson` json,
	`keyRisksJson` json,
	`pricePrediction1yr` text,
	`pricePrediction3yr` text,
	`pricePrediction5yr` text,
	`pricePredictionNarrative` text,
	`pricePredictionConfidence` varchar(16) DEFAULT 'medium',
	`buyersGuideTop5Json` json,
	`buyersGuideRedFlagsJson` json,
	`bestSpec` text,
	`worstSpec` text,
	`marketContextNarrative` text,
	`peerComparisonNarrative` text,
	`scoringMethodologyNarrative` text,
	`llmModel` varchar(64) DEFAULT 'gpt-4o',
	`generatedAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `model_llm_content_id` PRIMARY KEY(`id`),
	CONSTRAINT `model_llm_content_modelKey_unique` UNIQUE(`modelKey`)
);
